
security:
  oauth2:
    resource:
      filter-order: 3
      userInfoUri: http://localhost:9999/user/user
      preferTokenInfo: false
    sso:
      login-path: http://localhost:9999/user/login
server:
  port: 9999
  context-path: /user
spring:
  application:
    name: service-user
  datasource:
    url: jdbc:mysql://localhost/ecandy_user
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.ecandy.user
logging:
  level:
    org.springframework: DEBUG
    org.springframework.security: DEBUG
