package com.ecandy.product.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.ecandy.product.model.Product;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    @Delete({
            "delete from product",
            "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    @Insert({
            "insert into product ( name, ",
            "quantity, price)",
            "values ( #{name,jdbcType=VARCHAR}, ",
            "#{quantity,jdbcType=INTEGER}, #{price,jdbcType=DOUBLE})"
    })
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "id, name, quantity, price",
            "from product",
            "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.ecandy.product.mapper.ProductMapper.BaseResultMap")
    Product selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    @Update({
            "update product",
            "set name = #{name,jdbcType=VARCHAR},",
            "quantity = #{quantity,jdbcType=INTEGER},",
            "price = #{price,jdbcType=DOUBLE}",
            "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Product record);

    List<Product> selectAll();

    @Select({
            "select",
            "id, name, quantity, price",
            "from product",
            "where name = #{name,jdbcType=VARCHAR}"
    })
    Product selectByName(String name);
}