spring:
  application:
    name: api-gateway
server:
  port: 17900
#配置eureka服务地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka
  instance:
    prefer-ip-address: true
zuul:
  host:
    #zuul配置
    max-per-route-connections: 50
    max-total-connections: 200
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  #关闭重试机制
  retryable: true
  routes:
    product:
      #说明: path不是微服务的地址而是自己定义的地址如果微服务地址为 /api/product 则此处访问地址为: /product/api/product
      path: /product/**
      serviceId: service-product
    price:
      path: /price/**
      serviceId: servcie-price
    sales-order:
      path: /sales-order/**
      serviceId: servcie-sales-order
    user:
      path: /user/**
      serviceId: servcie-user
      url: http://localhost:9999/
  include-debug-header: true
  add-proxy-headers: true
security:
  oauth2:
    client:
      access-token-uri: http://localhost:9999/user/oauth/token
      user-authorization-uri: http://localhost:9999/user/oauth/authorize
      client-id: api-gateway
      client-secret: api-gateway
    resource:
      user-info-uri: http://localhost:9999/user/user
      prefer-token-info: false
#开启debug模式
debug: true
