server:
  port: 8100
eureka:
  instance:
    hostname: eureka-server
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
    register-with-eureka: false
    fetch-registry: false
